version: '3.3'
services:
  auth-app:
    container_name: auth-app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=72h'
      - '--storage.tsdb.wal-compression'
