name: E2E tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Stop and remove existing containers
        run: |
          docker stop $(docker ps -aq) || true
          docker rm $(docker ps -aq) || true

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Create .env file
        run: |
          echo "sender_email=${{ secrets.sender_email }}" >> .env
          echo "sender_password=${{ secrets.sender_password }}" >> .env
          echo "test_email=${{ secrets.test_email }}" >> .env
          echo "test_code=${{ secrets.test_code }}" >> .env

      - name: Build and start containers
        run: |
          docker-compose build
          docker-compose up -d

      - name: List running containers
        run: docker ps

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave requests

      - name: Wait for Prometheus metrics endpoint
        run: |
          timeout 90s bash -c 'until curl -v -s http://localhost:8000/metrics > /dev/null; do sleep 5; done'

      - name: Run tests
        run: |
          cd features/steps
          behave

      - name: Save Prometheus metrics
        run: |
          curl -s http://localhost:8000/metrics > prometheus_metrics.txt || echo "Metrics not available" > prometheus_metrics.txt
        continue-on-error: true

      - name: Display Prometheus metrics in logs
        run: |
          cat prometheus_metrics.txt

      - name: Upload Prometheus metrics as artifact
        uses: actions/upload-artifact@v3
        with:
          name: prometheus-metrics
          path: prometheus_metrics.txt

      - name: Stop containers
        run: |
          docker-compose down
